name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENCE.txt'
      - 'release/**'
      - 'dist/**'

permissions:
  contents: write

jobs:
  windows-executable:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'
    
      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Required Libraries
        run: pip install -r requirements.txt

      - name: Run PyInstalller
        run: pyinstaller --onedir --noconsole --name GTMonitor main.py

      - name: Update Release Folder
        env:
          MESSAGE: "[Automated Windows Build]"
          AUTHOR: "Github Actions"
          EMAIL: "dmohanja@users.noreply.github.com"
        run: |
          rm release/ -r
          md release
          Compress-Archive ./dist/* -Destination ./release/GTMonitor.zip
          git config --global user.name '${{ env.AUTHOR }}'
          git config --global user.email '${{ env.EMAIL }}'
          git add release/GTMonitor.zip
          git commit -m '${{ env.MESSAGE }}'
          git push
      
        

          
